name: mirelle

services:
  api:
    build: 
     context: .
     dockerfile: api.Dockerfile
    image: ${ECR_REPO_URL}:latest
    ports:
      - "80:3000"
    command: ["python3", "-m", "uvicorn", "api:app"]
