FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY client.py .
COPY templates ./templates

EXPOSE 8080

CMD ["uvicorn", "client:app", "--host=0.0.0.0", "--port=8080"]