services:
  video-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=ap-southeast-2
      - DYNAMODB_TABLE=n11715910-a2


  video-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001"
    depends_on:
      - video-api
